### PR TITLE
[WorkInProgress] #188: create extension point to allow append VM args, system properties and ENV vars to launch configuration

### PR DESCRIPTION
**Pull request by missedone**
in this PR, create an extension point that allow 3rd party (e.g. more detail about maven integration later) to append VM args, system properties and environments from metadata file of project management tool, for example, pom.xml of maven, *.gradle of gradle, etc.

for instance, the PR also implement a new plugin for maven integration, which parse the plugin configuration of maven-surefire-plugin and maven-failsafe-plugin from pom.xml, and append them to TestNG process when launch.
here is what the preference looks like:
testng_maven_pref

as now maven integration is implemented in a separate plugin (thanks for eclipse extension point mechanism), we can see this new plugin is optional, user can select install it or not. if user want to install the main testng plugin, that's fine, everything works as before. if he/she install the maven integration plugin as well, they can take advantage of the new features.
testng_maven

CC: @cbeust , @juherr

### CODE REVIEW

**Comment by cbeust** [comment]
Wow, that is some seriously impressive work, @missedone, congratulations!

Probably too big for me to understand everything by just reviewing it but I'll take a quick look anyway.

**Comment by zkendall** [comment]
When'll this make it into the eclipse marketplace?

**Comment by juherr** [comment]
:+1:

**Comment by cbeust** [comment]
I just pushed the new version but somehow, it's appearing as 6.9.9.xxx even
though I set its version to be 6.9.10.xxx. Anyway, try it and report back.

-- 
Cédric

**Comment by missedone** [comment]
@cbeust 

this is looks not right:
testng_install

there should be "TestNG M2E Integration (Optional)" as well.

**Comment by missedone** [comment]
do you see something like this under updatesite, there should be 'org.testng.eclipse.maven.feature.xxxx' etc.
testng_updatesite

**Comment by cbeust** [comment]
Yes, I think your changes messed up the upload script that I use, I need to
fix it.

-- 
Cédric

**Comment by juherr** [comment]
Why not using bintray? http://blog.bintray.com/2014/03/11/hosting-your-eclipse-update-site-p2-on-bintray-com/

**Comment by cbeust** [comment]
The official URLhas been http://beust.com/eclipse for a while, not sure I
want to go through the trouble of adjusting the build and setting up
redirects...

-- 
Cédric

**Comment by cbeust** [comment]
@missedone Do your latest changes modify what needs to be uploaded to the update site?

Right now, all the upload script does is upload the content of `testng-eclipse-update-site/target/site`, is this still correct?

**Comment by missedone** [comment]
@cbeust , everything is under `target/site/`, did you check the content on your file server (updatesite server), are all files there?

**Comment by cbeust** [comment]
Ok I found the problem, I see the correct plugins now. Can you try and
confirm?

-- 
Cédric

**Comment by missedone** [comment]
nice, i can install the new plugins and it works, thanks

**Comment by zkendall** [comment]
Thank you all for your work!

Is "http://beust.com/eclipse" the url we're supposed to use? If so, it's not documented anywhere. When I went to the marketplace, it showed the update, but NOT the optional addition. When I used that URL though it showed the optional addition.

**Comment by cbeust** [comment]
The Eclipse market place should pick it up from http://beust.com/eclipse
eventually, I don't know how often they refresh. Let me know if they don't.

-- 
Cédric


On Sat, Nov 28, 2015 at 2:13 PM, Zachariah Kendall <notifications@github.com

**Pull request merged**
