### PR TITLE
testng #912: update testng-remote jar with serialVersionUUID explicitly set

### PR DESCRIPTION
**Pull request by missedone**
sync with https://github.com/cbeust/testng/pull/913

### CODE REVIEW

**Comment by missedone** [comment]
hi @cbeust 
please update the testng.jar in plugin once you merge PR https://github.com/cbeust/testng/pull/913
thanks

**Comment by cbeust** [comment]
I just pushed a new plug-in with your serialVersionUuid change, can you try?

**Comment by missedone** [comment]
yes, it works.
could you merge this PR as well since i synced the changes from https://github.com/cbeust/testng/pull/913

**Comment by cbeust** [comment]
Done!

**Pull request merged**
