### PR TITLE
Add support for code mining for test methods and test classes.

### PR DESCRIPTION
**Pull request by gayanper**
Change-Id: I5d3504be0675e02e28c8b875aae839d34859f616
Signed-off-by: gayanper <gayanper@gmail.com>

### CODE REVIEW

**Comment by missedone** [comment]
link #483

**Comment by missedone** [comment]
@gayanper LGTM, could you update the CHANGES.md to include this feature. thx

**Comment by gayanper** [comment]
Done please check if the description is clear enough, i'm not really good at descriptions :)

**Comment by missedone** [comment]
LGTM, thanks for the contribution

**Pull request merged**
