### PR TITLE
issue #206: lauching test is failing with non maven projects

### PR DESCRIPTION
**Pull request by missedone**
fixed issue #206

### CODE REVIEW

**Comment by kpassoubady** [comment]
This issue is reoccurring again. Same exact error message. The version testNG installed is 6.9.10.

Can you please take a look at it. 

An internal error occurred during: "Launching src.testng.xml".
java.lang.NullPointerException

**Comment by missedone** [comment]
hi @cbeust 
could you build a new version of testng plugin?
thanks

**Comment by cbeust** [comment]
Done.

-- 
Cédric

**Comment by kpassoubady** [comment]
Thanks Cedric. I have uninstalled and re-installed the eclipse testng plugin with (http://beust.com/eclipse)  I see that you have a new version of plugin from (http://beust.com/eclipse-old) and checked the plugin version after installaling, it shows the same. (see the attached screenshot).
testng-2015-12-13_6-32-42

Now receiving different error message:
java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786)
	at java.io.ObjectOutputStream.<init>(ObjectOutputStream.java:247)
	at org.testng.remote.strprotocol.SerializedMessageSender.sendMessage(SerializedMessageSender.java:24)
	at org.testng.remote.strprotocol.MessageHub.sendMessage(MessageHub.java:43)
	at org.testng.remote.RemoteTestNG$RemoteSuiteListener.onStart(RemoteTestNG.java:257)
	at org.testng.SuiteRunner.invokeListeners(SuiteRunner.java:208)
	at org.testng.SuiteRunner.run(SuiteRunner.java:266)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)

**Comment by kpassoubady** [comment]
The sample code repository:
https://github.com/kpassoubady/testng-order

**Comment by kpassoubady** [comment]
Another request in the wrong place:
http://testng.org/javadocs/index.html

The javadoc is outdated (don't see SoftAssert Class), can you re-deploy the latest javadoc. 
Appreciated.

**Comment by missedone** [comment]
@kpassoubady 
could you try with the latest version of plugin
thanks

**Comment by kpassoubady** [comment]
I have tested with the latest version. All works as expected.
Sorry for the delay in my response.

**Comment by kpassoubady** [comment]
http://beust.com/eclipse-old/eclipse_6.9.10.201512150346

that is the version i ran my code. I did not receive the error mentioned previously. 
Thanks for all your help. Appreciated :-)

**Pull request merged**
