### PR TITLE
fixed "Classes from WAR project exported with `<attachClasses>true</attachClasses>` are not visible if JBoss Tools Maven Packaging Configurator is installed"

### PR DESCRIPTION
**Pull request by missedone**
fix for https://github.com/cbeust/testng/issues/1209 by reverting PR #252 for #251

### CODE REVIEW

**Comment by missedone** [comment]
for the record, according the source code of M2E, `org.eclipse.m2e.jdt.internal.MavenClassifierManager.getClassifierClasspathProvider(IMavenProjectFacade, String)`

```java
  public IClassifierClasspathProvider getClassifierClasspathProvider(IMavenProjectFacade project, String classifier) {
    List<IClassifierClasspathProvider> allProviders = getClassifierClasspathProviders(classifier);
    List<IClassifierClasspathProvider> compatibleProviders = new ArrayList<IClassifierClasspathProvider>();

    if(allProviders != null) {
      for(IClassifierClasspathProvider p : allProviders) {
        if(p.applies(project, classifier)) {
          compatibleProviders.add(p);
        }
      }
    }

    switch(compatibleProviders.size()) {
      case 0:
        //nothing here
        break;
      case 1:
        return compatibleProviders.get(0);
      default:
        //TODO display/log error message
    }
    return NO_OP_CLASSIFIER_CLASSPATH_PROVIDER;
  }
```

we can see it supports only one ClassifierClasspathProvider, but in our case, there were two, one comes from m2e-wtp `org.eclipse.m2e.wtp.warClassesClassifierClasspathProvider`, and the other is TestNG `org.testng.eclipse.maven.WarClassesClassifierClasspathProvider`.

till then I realized `org.testng.eclipse.maven.WarClassesClassifierClasspathProvider` was duplicating with `org.eclipse.m2e.wtp.warClassesClassifierClasspathProvider`, since most of the case of web development having Eclipse JEE package installed (which already include m2e-wtp), so this was potential issue.
Instead of making TestNG plugin unnecessary smart, I prefer to leave the `<attachClasses>true</attachClasses>` to official m2e wtp plugin.

CC: @michaldo

**Comment by michaldo** [comment]
I realized that classes from WAR are not visible due bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=502349
When I remove <classifier>classes</classifier> from pom.xml, classes are visible. 
Error is reproducible regardless of m2e-wtp is installed or not
(I don't know why  m2e-wtp solved my original problem)

**Comment by missedone** [comment]
@michaldo , I'm not sure what do you mean "classes from WAR are not visible", I ran your test case of project [testng-issue](https://github.com/michaldo/testng-issue) successfully, with plugin spec below:
* Eclipse Neon SDK
* TestNG Eclipse Plugin 6.10.0.201612030230
* m2e [1.8 milestone](http://download.eclipse.org/technology/m2e/milestones/1.8/) 1.8.0.20160809-1624: 
* m2e-wtp 1.3.1 https://www.eclipse.org/m2e-wtp/download/

**Comment by michaldo** [comment]
@missedone , if you take test case project https://github.com/michaldo/testng-issue and change in wf/pom.xml `<attachClasses>true</attachClasses>` -> `<archiveClassess>true</archiveClassess>`, you will fail.
But if delete `<classifier>classes</classifier>` in demo/pom.xml, you will pass again.

It happens regardless m2e-wtp is installed or not. Then I deduce core problem is located in m2e, but m2e-wtp can help with `attachClasses`

**Comment by missedone** [comment]
oh, I oversaw `archiveClassess` vs. `attachClasses`, thanks for the clarification.

**Pull request merged**
