### PR TITLE
Debundle Guava from the plugin

### PR DESCRIPTION
**Pull request by mbooth101**
Instead of embedding guava libs inside the plugin bundle, guava
can these days be consumed from the Eclipse platform update site
as a real OSGi bundle.

This change also drops usage of Guava APIs that are deprecated
since the introduction of Java 7 "diamond" syntax for collections.

For example of APIs that are considered deprecated, see:
http://google.github.io/guava/releases/21.0/api/docs/com/google/common/collect/Lists.html#newArrayList--

Since this plugin has a BREE of Java 7, there is no longer any benefit
or advantage of using the Guava API instead of the new Java 7
diamond syntax.

### CODE REVIEW

**Comment by missedone** [comment]
@mbooth101, looks great.
Could you confirm the guava OSGi bundle will be installed automatically if people don't have it in their eclipse instance.

**Comment by mbooth101** [comment]
@missedone TBH it's pretty difficult to find an Eclipse download that does not already come with Guava -- Looking at Neon distributions I already had downloaded, the IDEs for Committers, Java Dev, Java EE Dev, and C/C++ Dev all ship with the Guava bundle.

So I had to download the raw Eclipse Platform SDK from [this page](http://download.eclipse.org/eclipse/downloads/drops4/R-4.6.2-201611241400/) in order to test the installing the TestNG plugin into an Eclipse that did not already contain guava. I can confirm that installing TestNG plugin works fine and successfully pulls in Guava from the Eclipse Neon update site.

Maybe worth noting that m2e also has a dep on the Guava bundle, so all users that have the TestNG optional m2e extension installed probably already have the Guava bundle installed anyway.

**Comment by missedone** [comment]
@mbooth101, I just tried on Eclipse Kepler JEE Bundle, install the new TestNG plugins (build with debundle guava), the installation failed since missing guava.
screenshot at feb 25 17-27-58

I think one solution is to add [Orbit update site](http://download.eclipse.org/tools/orbit/downloads/) into TestNG [composite update site](http://dl.bintray.com/testng-team/testng-eclipse-release/), or do you think is there any other way that can suggest Eclipse where to find the missing dependency when the installation cannot satisfy dependnecy?

**Comment by mbooth101** [comment]
@missedone Yes, if we switch the update site project to **eclipse-repository** packaging, instead of using the obsolete **eclipse-update-site** packaging, we can include bundles from the target platform into the TestNG update site, so that users.

See my latest commit to this branch -- the generated update site now also includes the guava bundle for those who need it.

**Comment by missedone** [comment]
LGTM

I'd like to merge the PR once:
1. conflicts resolved
2. the follow empty "Uncategorized" looks confusing, could you remove it?
screenshot at mar 01 07-43-45

thanks

**Comment by mbooth101** [comment]
Okay, I rebased my branch onto latest master, and added the guava bundle to the "TestNG" category, so there should no longer be anything "Uncategorised"

**Comment by missedone** [comment]
thx for the contribution, just updated the changelog: https://github.com/cbeust/testng-eclipse/blob/master/CHANGES.md

**Comment by missedone** [comment]
the new build is available on beta channel now: http://beust.com/eclipse-beta

**Pull request merged**
