### PR TITLE
Support for PDE launch and update site reorganization

### PR DESCRIPTION
**Pull request by piotrtomiak**

### CODE REVIEW

**Comment by piotrtomiak** [comment]
@cbeust we are using TestNG for Eclipse plugin tests and it would be extremely convenient if we wouldn't have to maintain a fork of your repository. Are you willing to consider the contribution?

**Comment by JnRouvignac** [comment]
What is commit 0f89950 ? What is it changing in the plugin?
It spans over 1400+ files which is way too much.
It also contains .class files which it should never have.

Could you consider splitting it in single purpose commits so they can be reviewed more easily?

**Comment by piotrtomiak** [comment]
Thanks for looking at this PR!

This big commit is aiming at reorganization of the structure of repository. The problem is that to be able to launch PDE env with test-ng all plugins have to be correctly set up. That is: there has to be a runtime and dev-time set of features. Most of the changes are just renames and refactorings; unfortunately github diff doesn't show them well.

Class files are coming from test-ng jar. It has to be bundled as a plugin. At the time test-ng jar did not have an OSGi manifest. It has now, so we could just include it directly without any workarounds. In this context it sounds as if moving to Maven based build for the whole feature is a very good idea.

I am aware that this PR has to be created again and that it has to be much more readable :) Initially, Cedrik asked me to push what I have had as a starting point, and what you see is what I have pushed back than. I am willing to work on this and contribute a support for PDE launching and do any required maintenance, however, since this requires some amount of work, I need to know if you are interested in such a contribution in first place.

**Comment by cbeust** [comment]
A few thoughts:

- As @JnRouvignac pointed out, this is a very big pull request and I don't think it's very realistic to expect it to be reviewed as it is.
- Some of these commits look like they can be moved to their own PR (such as the GUI blocking fix) since they would benefit both the current plug-in and the task you are trying to achieve. I'm much more opened merging these first since I can assess them and users other than yourself will benefit from it.
- Avoid mixing code changes with refactorings in your pull request: they increase the size of the PR for no reason and they make it hard to review what has actually changed. For example, this:

```
- if (!argv.contains(CommandLineArgs.LISTENER)) {
- argv.add(CommandLineArgs.LISTENER);
- argv.add(reportersContributors.toString().trim());
+ if (!programArguments.contains(CommandLineArgs.LISTENER)) {
+ programArguments.add(CommandLineArgs.LISTENER);
+ programArguments.add(reportersContributors.toString().trim());
```
I always suggest having separate commits: code changes followed by a commit called "refactoring" or "formatting" or whatever, showing that this commit is not supposed to change any logic.

As for whether I'm interested in this PR, I'm not sure, I need to assess the benefits of PDE launching and make sure your change will benefit more than just the author of the PR...

**Comment by piotrtomiak** [comment]
@cbeust I totally agree with all the points. As I said, this PR was meant to provide kind of an overview of changes the support for PDE launching brings in, so that we can talk on whether you want that kind of changes in (that was based on our initial conversation 2 years ago). Once you decide you want to go this path, I will prepare a separate PR, which will conform to all of the standards. Refactoring will be in separate commits and it will be step by step. Code changes will happen in separate commits. Creating a separate PR for the UI locking issue first sounds like a very good idea.

Main points of the PR are:
- refactoring of repository to have separate folders for plugins and features.
- split of the main plugin to devtime and runtime (includes extracting testng to a separate bundle)
- provide PDE test harness plugin
- Mavenize projects and build process (new; makes much easier to include the latest testng binaries in the build)

I think that from this PR the whole TestNG community can benefit, as it will allow for bigger exposure of the tooling in eclipse community. Being able to run a Test-NG suite on a running eclipse instance is, in my opinion, one of the biggest missing features in current implementation. Adding it will make TestNG available for all eclipse plug-in developers. I personally feel TestNG is better designed than JUnit and easier to use, and that's why we want to use it for testing MyEclipse plug-ins. I don't think that this is an isolated case :)

**Comment by missedone** [comment]
@piotrtomiak , looks like you did quite big effort on this PR, let's don't lose it. 

> provide PDE test harness plugin

**this is a quite interesting part**, could you create a PR based on recent master branch?

> refactoring of repository to have separate folders for plugins and features.

this has been done.

> split of the main plugin to devtime and runtime (includes extracting testng to a separate bundle)

this has been done in recent PR #325 for story #287 that de-bundle TestNG jars

> Mavenize projects and build process (new; makes much easier to include the latest testng binaries in the build)

this has been done with maven tycho plugin.

thanks again for your passion and effort.

**Comment by piotrtomiak** [comment]
Hello! It's been over 2 years since my initial PR. I hope I will be able to find time to update the code now.

**Pull request closed without merging**
