### PR TITLE
Issue/149 better way to compare the java version compatibility

### PR DESCRIPTION
**Pull request by missedone**
use org.osgi.framework.Version.compareTo() to compare the java version compatibility rather than String.compareTo()

### CODE REVIEW

**Comment by missedone** [comment]
this is verified by running TestNG test with Java6, Java7 and Java8
when run with Java6, it's is expected to see a error dialog saying something like "VM version 1.6.0 is invalid, Java 1.7 or above is required for running TestNG."

**Comment by cbeust** [comment]
Much better, I like it! Did you test with "1.10" just to make sure?

**Comment by missedone** [comment]
It's OK though i did not test with "1.10", it relies on the implementation of `org.osgi.framework.Version.compareTo(Version)`:
> A version is considered to be equal to another version if the major, minor and micro components are equal and the qualifier component is equal (using String.compareTo).

```
	private final int			major;
	private final int			minor;
	private final int			micro;
	private final String		qualifier;
```

**Comment by SpiffyCoffee** [comment]
Hi all, this change ends up breaking the plugin for users still using Eclipse 3.6 (Helios) and for the poor saps (me) who are stuck using the Helio-based versions of RAD (8.0 and 8.5) at work

The reason is the compareTo that takes in Version
`org.osgi.framework.Version.compareTo(Version)`
wasn't introduced until OSGi 1.6 in Eclipse 3.7 (Indigo) 

Attempting to run a test in the older Eclipse/RAD results in
```
An internal error occurred during: "Launching nameOfTest".
org/osgi/framework/Version.compareTo(Lorg/osgi/framework/Version;)I
```

**Comment by cbeust** [comment]
@missedone Do you think we can have this functionality in a way tha't s compatible with 3.6?

**Comment by missedone** [comment]
yep, fixed in PR #183

**Comment by SpiffyCoffee** [comment]
Thanks guys! I can confirm the plugin now works in RAD 8.5.

FYI, I was able to build the plugin from the latest revision but ran into a different runtime issue. 
```
java.lang.AbstractMethodError: org/testng/ITestRunnerFactory.newTestRunner(Lorg/testng/ISuite;Lorg/testng/xml/XmlTest;Ljava/util/Collection;)Lorg/testng/TestRunner;
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:587)
	at org.testng.SuiteRunner.init(SuiteRunner.java:161)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:114)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1266)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1253)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1107)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
```
This was with jdk_1.7 in Eclipse Mars. It looks like every commit after f28a24c8c1edf66863be33b28fbc4d3bc397e9a4 has this issue. I was able to successfully build and run that revision and ended up back porting missedone's fix in order to test it in RAD

**Comment by missedone** [comment]
@SpiffyCoffee 
it most likely caused by PR #171 
could you share a small project for me to re-produce the issue, and see if I can fix it easily

**Comment by SpiffyCoffee** [comment]
@missedone https://github.com/SpiffyCoffee/testNG-plugin-test
Here you go, just a dummy project with one class and one TestNG test. Performing Right-click -> Run As -> TestNG gives me the error.

**Pull request merged**
