### PR TITLE
Refactor/133 restructure folder to facilitate eclipse tycho build plugin

### PR DESCRIPTION
**Pull request by missedone**
as described in issue #133, refactor the code structure to facilitate eclipse tycho plugin to build testng eclipse plugins.

see instructions to build plugins and update the version numbers:
https://github.com/missedone/testng-eclipse/blob/refactor/133/DEVELOP.md

> Now, building testng eclipse plugin update site can be as simple as the single command below (provided that you have maven installed already): `mvn -e clean package`

### CODE REVIEW

**Comment by missedone** [comment]
@cbeust 
as the folders were restructured, you need to delete the projects from your eclipse workspace, and re-import the "Existing eclipse projects into workspace"

though it's recommended to build with maven command line, it does not prevent you from building plugin inside eclipse:)

**Comment by cbeust** [comment]
Thanks, @missedone, this is a scary pull request. Can you give me a sense of how much of this PR is just moving files around and how much is actually code changes?

**Comment by missedone** [comment]
yes, it is:)

actually, no code change introduced.

all the plugin source code moved into `org.testng.eclipse`
`testng-eclipse-feature` was renamed to `org.testng.eclipse.feature`
`testng-eclipse-update-site` was renamed to `uplatesite`

also be noticed that, some old ant style build filed are removed:

* autobuild.README
* autobuild.plugin.properties
* autobuild.plugin.xml
* eclipse-path.xml
* testng-eclipse-update-site/autobuild.site.properties
* testng-eclipse-update-site/autobuild.site.xml
* testng-eclipse-update-site/artifacts.jar
* testng-eclipse-update-site/content.jar
* testng-eclipse-update-site/index.html
* testng-eclipse-update-site/logs.zip
* testng-eclipse-update-site/nohup.out
* testng-eclipse-update-site/features/
* testng-eclipse-update-site/plugins/

last, the feature id was renamed to 'org.testng.eclipse.feature' from 'org.testng.eclipse', as it should be matching with the artifactid in org.testng.eclipse.feature/pom.xml

**Comment by missedone** [comment]
or, I can revert the changes of:
* testng-eclipse-feature was renamed to org.testng.eclipse.feature
* testng-eclipse-update-site was renamed to uplatesite

which means only plugin source code was moved to new folder, this can introduce less changes in the PR

**Comment by missedone** [comment]
OK, it's done, now the PR is smaller, in the [diff view](https://github.com/cbeust/testng-eclipse/pull/135/files) you can clearly see most of the files are 'File renamed without changes'

**Comment by cbeust** [comment]
I'm testing the changes, everything is building and I was able to generate the new update site, however, Eclipse doesn't seem to recognize anything in it:

image

Am I missing something?

**Comment by cbeust** [comment]
@missedone Never mind, I figured it out: the site is actually under `target/site`. The update seems to be working, I have some additional testing to do (update the upload script and all) but overall, this is looking great.

**Comment by cbeust** [comment]
Thanks, @missedone, this is awesome!

**Comment by cbeust** [comment]
@missedone Can you email me to wrap up about this pull request?

Thanks!

**Pull request merged**
