### PR TITLE
add additional Exception catches to...

### PR DESCRIPTION
**Pull request by nickboldt**
add additional Exception catches to CustomSuite and ConvertToYamlAction

Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
@missedone Here's the revised version of #343 you requested. Sorry for the delay. When is 6.12 scheduled to be released? See also https://github.com/cbeust/testng/pull/1521 -- not sure if that's a valid fix. Also wondered if you wanted to do this change in testng-eclipse-plugin/META-INF/MANIFEST.MF to depend on the latest testng, or if 6.9.12+ is still a valid minimum version.

`- org.testng;bundle-version="[6.9.12,7.0.0)",
+ org.testng;bundle-version="[6.12,7.0.0)",
`

**Comment by missedone** [comment]
hi @nickboldt , 6.9.12+ is still a valid minimum version range

in PR #325, I de-bundled TestNG jars with TestNG P2 repo. since the OSGified TestNG version before 6.9.12 causes some class loading issue within TestNG Eclipse Plugin. 
because TestNG eclipse plugin has an embedded testng-remote jar (which was extracted from TestNG, and removed the remote package since TestNG 6.9.12), while the OSGified TestNG version before 6.9.12 still contains obsolete remote package hence cause the class loading issue.

**Comment by missedone** [comment]
I think, technically speaking, TestNG 6.12 was released, but not yet sync to Central Maven Repo.
there's two build system used by TestNG, Kobalt and Gradle. normally Kobalt was used to do the release. and, yep, this is confusing and easily out of sync between build.kt and build.gradle.

**Comment by nickboldt** [comment]
Further confusing is the fact that there's a https://github.com/cbeust/testng/blob/master/README.build which talks about needing Ivy to build with Ant. How many build systems have you guys used here? :)

**Comment by cbeust** [comment]
Yeah, sorry for the confusion. The official build is Gradle, everything else can be ignored.

**Comment by cbeust** [comment]
Note: I deleted `README.build`.

**Pull request merged**
